// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addRefreshToken = `-- name: AddRefreshToken :exec
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at, revoked_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    NULL
)
`

type AddRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, addRefreshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const getRefreshTokenFromUserID = `-- name: GetRefreshTokenFromUserID :one
SELECT token FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) GetRefreshTokenFromUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenFromUserID, userID)
	var token string
	err := row.Scan(&token)
	return token, err
}

const getRefreshTokenStatus = `-- name: GetRefreshTokenStatus :one
SELECT revoked_at FROM refresh_tokens WHERE token = $1
`

func (q *Queries) GetRefreshTokenStatus(ctx context.Context, token string) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenStatus, token)
	var revoked_at sql.NullTime
	err := row.Scan(&revoked_at)
	return revoked_at, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW(), updated_at = NOW() WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, token)
	return err
}
